export const PARSER_VERSION = '2.0.0-local';

export const SECTION_ALIASES = {
  personal: [
    'contact',
    'contact information',
    'personal details',
    'profile',
    'summary',
    'professional summary',
    'about me',
    'objective',
  ],
  experience: [
    'experience',
    'work experience',
    'professional experience',
    'employment history',
    'career history',
    'work history',
    'professional journey',
    'career',
    'internships',
  ],
  education: [
    'education',
    'academic background',
    'qualifications',
    'educational qualifications',
    'academic history',
  ],
  skills: [
    'skills',
    'technical skills',
    'core skills',
    'technologies',
    'technical expertise',
    'competencies',
  ],
  projects: [
    'projects',
    'personal projects',
    'academic projects',
    'selected projects',
    'key projects',
  ],
  certifications: [
    'certifications',
    'certificates',
    'professional certifications',
    'credentials',
  ],
  languages: ['languages'],
  awards: ['awards', 'achievements'],
  publications: ['publications'],
  volunteer: ['volunteer', 'volunteer experience'],
  training: ['training', 'courses'],
  interests: ['interests', 'hobbies'],
};

export const LOCATION_ALIASES = [
  ['bangalore', 'Bengaluru'],
  ['bangaluru', 'Bengaluru'],
  ['bengaluru', 'Bengaluru'],
  ['trivandrum', 'Thiruvananthapuram'],
  ['thiruvananthapuram', 'Thiruvananthapuram'],
  ['bombay', 'Mumbai'],
  ['mumbai', 'Mumbai'],
  ['madras', 'Chennai'],
  ['chennai', 'Chennai'],
  ['cochin', 'Kochi'],
  ['kochi', 'Kochi'],
  ['new delhi', 'New Delhi'],
  ['delhi ncr', 'Delhi NCR'],
  ['hyderabad', 'Hyderabad'],
  ['pune', 'Pune'],
  ['remote - india', 'Remote, India'],
  ['remote india', 'Remote, India'],
  ['remote', 'Remote'],
];

export const TITLE_ALIASES = [
  ['sde', 'Software Engineer'],
  ['software developer', 'Software Developer'],
  ['software engineer', 'Software Engineer'],
  ['frontend engineer', 'Frontend Engineer'],
  ['front-end engineer', 'Frontend Engineer'],
  ['frontend developer', 'Frontend Developer'],
  ['front-end developer', 'Frontend Developer'],
  ['ui developer', 'UI Developer'],
  ['web developer', 'Web Developer'],
  ['senior software engineer', 'Senior Software Engineer'],
  ['sr. software engineer', 'Senior Software Engineer'],
  ['sr software engineer', 'Senior Software Engineer'],
  ['lead developer', 'Lead Developer'],
  ['technical lead', 'Technical Lead'],
  ['devops engineer', 'DevOps Engineer'],
  ['qa engineer', 'QA Engineer'],
  ['data engineer', 'Data Engineer'],
  ['data scientist', 'Data Scientist'],
];

export const SKILL_ALIASES = [
  { canonical: 'React', category: 'Frontend', aliases: ['react', 'reactjs', 'react.js'] },
  { canonical: 'Next.js', category: 'Frontend', aliases: ['next.js', 'nextjs'] },
  { canonical: 'Vue', category: 'Frontend', aliases: ['vue', 'vue.js', 'vuejs'] },
  { canonical: 'Angular', category: 'Frontend', aliases: ['angular', 'angularjs'] },
  { canonical: 'TypeScript', category: 'Languages', aliases: ['typescript', 'ts'] },
  { canonical: 'JavaScript', category: 'Languages', aliases: ['javascript', 'js', 'ecmascript'] },
  { canonical: 'HTML', category: 'Frontend', aliases: ['html', 'html5'] },
  { canonical: 'CSS', category: 'Frontend', aliases: ['css', 'css3', 'tailwind css', 'tailwindcss'] },
  { canonical: 'Redux', category: 'Frontend', aliases: ['redux', 'redux toolkit'] },
  { canonical: 'Node.js', category: 'Backend', aliases: ['node', 'node.js', 'nodejs'] },
  { canonical: 'Express', category: 'Backend', aliases: ['express', 'express.js', 'expressjs'] },
  { canonical: 'NestJS', category: 'Backend', aliases: ['nestjs', 'nest.js'] },
  { canonical: 'Python', category: 'Languages', aliases: ['python', 'python3'] },
  { canonical: 'Django', category: 'Backend', aliases: ['django'] },
  { canonical: 'Flask', category: 'Backend', aliases: ['flask'] },
  { canonical: 'Java', category: 'Languages', aliases: ['java'] },
  { canonical: 'Spring Boot', category: 'Backend', aliases: ['spring boot', 'springboot'] },
  { canonical: 'Go', category: 'Languages', aliases: ['go', 'golang'] },
  { canonical: 'Rust', category: 'Languages', aliases: ['rust'] },
  { canonical: 'C++', category: 'Languages', aliases: ['c++'] },
  { canonical: 'C#', category: 'Languages', aliases: ['c#', 'dotnet', '.net'] },
  { canonical: 'PostgreSQL', category: 'Database', aliases: ['postgresql', 'postgres', 'postgres sql'] },
  { canonical: 'MySQL', category: 'Database', aliases: ['mysql'] },
  { canonical: 'MongoDB', category: 'Database', aliases: ['mongodb', 'mongo db', 'mongo'] },
  { canonical: 'Redis', category: 'Database', aliases: ['redis'] },
  { canonical: 'SQLite', category: 'Database', aliases: ['sqlite'] },
  { canonical: 'Docker', category: 'DevOps', aliases: ['docker'] },
  { canonical: 'Kubernetes', category: 'DevOps', aliases: ['kubernetes', 'k8s'] },
  { canonical: 'Terraform', category: 'DevOps', aliases: ['terraform'] },
  { canonical: 'AWS', category: 'Cloud', aliases: ['aws', 'amazon web services'] },
  { canonical: 'GCP', category: 'Cloud', aliases: ['gcp', 'google cloud', 'google cloud platform'] },
  { canonical: 'Azure', category: 'Cloud', aliases: ['azure', 'microsoft azure'] },
  { canonical: 'CI/CD', category: 'DevOps', aliases: ['ci/cd', 'cicd', 'continuous integration', 'continuous deployment'] },
  { canonical: 'Git', category: 'Tools', aliases: ['git'] },
  { canonical: 'Linux', category: 'Tools', aliases: ['linux', 'unix'] },
  { canonical: 'Jest', category: 'Testing', aliases: ['jest'] },
  { canonical: 'Cypress', category: 'Testing', aliases: ['cypress'] },
  { canonical: 'GraphQL', category: 'Backend', aliases: ['graphql'] },
  { canonical: 'REST API', category: 'Backend', aliases: ['rest api', 'restful api', 'restful'] },
  { canonical: 'React Native', category: 'Mobile', aliases: ['react native', 'reactnative'] },
  { canonical: 'Figma', category: 'Tools', aliases: ['figma'] },
  { canonical: 'Jira', category: 'Tools', aliases: ['jira'] },
  { canonical: 'Scrum', category: 'Process', aliases: ['scrum'] },
  { canonical: 'Agile', category: 'Process', aliases: ['agile'] },
  { canonical: 'TensorFlow', category: 'AI/ML', aliases: ['tensorflow'] },
  { canonical: 'PyTorch', category: 'AI/ML', aliases: ['pytorch'] },
  { canonical: 'Pandas', category: 'Data', aliases: ['pandas'] },
  { canonical: 'NumPy', category: 'Data', aliases: ['numpy'] },
  { canonical: 'Scikit-learn', category: 'AI/ML', aliases: ['scikit-learn', 'sklearn'] },
  { canonical: 'Kafka', category: 'Backend', aliases: ['kafka'] },
  { canonical: 'RabbitMQ', category: 'Backend', aliases: ['rabbitmq', 'rabbit mq'] },
  { canonical: 'Firebase', category: 'Cloud', aliases: ['firebase'] },
  { canonical: 'FastAPI', category: 'Backend', aliases: ['fastapi'] },
];

export const COMPANY_HINTS = [
  'inc',
  'llc',
  'ltd',
  'corp',
  'corporation',
  'technologies',
  'technology',
  'solutions',
  'systems',
  'services',
  'labs',
  'studio',
  'consulting',
  'group',
  'company',
  'co.',
  'pvt',
  'private limited',
];

export const DEGREE_ALIASES = [
  ['b.tech', 'Bachelor of Technology'],
  ['btech', 'Bachelor of Technology'],
  ['b.e.', 'Bachelor of Engineering'],
  ['be', 'Bachelor of Engineering'],
  ['b.sc', 'Bachelor of Science'],
  ['bsc', 'Bachelor of Science'],
  ['m.tech', 'Master of Technology'],
  ['mtech', 'Master of Technology'],
  ['m.sc', 'Master of Science'],
  ['msc', 'Master of Science'],
  ['mca', 'Master of Computer Applications'],
  ['mba', 'Master of Business Administration'],
  ['ph.d', 'Doctor of Philosophy'],
  ['phd', 'Doctor of Philosophy'],
];

export const MONTH_ALIASES = {
  jan: 0,
  january: 0,
  feb: 1,
  february: 1,
  mar: 2,
  march: 2,
  apr: 3,
  april: 3,
  may: 4,
  jun: 5,
  june: 5,
  jul: 6,
  july: 6,
  aug: 7,
  august: 7,
  sep: 8,
  sept: 8,
  september: 8,
  oct: 9,
  october: 9,
  nov: 10,
  november: 10,
  dec: 11,
  december: 11,
};
